[package]
name = "rust-lib"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.105"
console_error_panic_hook = { version = "0.1.7", optional = true }
serde = { version = "1.0.228", features = ["derive"]}
serde-wasm-bindgen = "0.6.5"

[profile.release]
opt-level = "s"

[features]
default = ["console_error_panic_hook"]
